# Generated by Django 3.1.6 on 2021-02-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('max_size', models.PositiveIntegerField(default=0)),
                ('id_key', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Vending',
            },
        ),
    ]
