# Generated by Django 3.1.6 on 2021-02-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vending',
            name='total_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
